### PR TITLE
Test multi dimentionnal queries

### PR DESCRIPTION
**Pull request by matthieusieben**

### CODE REVIEW

**Comment by matthieusieben** [comment]
These tests fail, proving there is something wrong with the implementation.

**Comment by matthieusieben** [comment]
Not sure how to fix them.

**Comment by malthe** [comment]
Depends on your editor. You can use some autoformatting plugin which automatically breaks lines. Also, if you run `npm run lint` it _should_ show you these errors.

**Comment by matthieusieben** [comment]
These can indeed be implemented in types tests.

**Comment by malthe** [comment]
I merged this either way along with the required fixes.

**Comment by matthieusieben** [comment]
https://github.com/malthe/ts-postgres/commit/58645cba8c6af310ff37d954d6786d1624922002#r36316782

**Pull request merged**
